version: '3.8'

services:
  dev:
    container_name: learn_english_dev
    image: node:14-alpine
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000

  prod:
    container_name: learn_english_prod
    image: node:14-alpine
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000